Repository kumoh42/pr_practice, pull requests merged in 2024-01, with the labels that each got.

#2 인사
  temp.py
Labels: question

#1 나의 자기소개를 해따
  temp.txt
Labels: enhancement

#3 abcd
  abcd.py
Labels: temp
